export { default as Hero } from './Hero'
export { default as Gameplay } from './Gameplay'
export { default as Tournament } from './Tournament'
export { default as Roadmap } from './Roadmap'
export { default as Team } from './Team'
export { default as Socials } from './Socials'
