export const BACKEND_BASE_URI = process.env.NEXT_PUBLIC_BACKEND_BASE_URI
export const NETWORK = process.env.NEXT_PUBLIC_NETWORK
export const ADMIN_ADDRESS = process.env.NEXT_PUBLIC_ADMIN_ADDRESS
export const TEMP_WALLET = process.env.NEXT_PUBLIC_TEMP_WALLET
export const DEFAULT_SIZE = process.env.NEXT_PUBLIC_DEFAULT_SIZE
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL
export const WEBSOCKET_URL = process.env.NEXT_PUBLIC_WEBSOCKET_URL
export const MOBILE_QUERY = '(max-width: 480px)'
export const TABLET_QUERY = '(max-width: 834px), (max-width: 950px) and (orientation: landscape)'
